#pragma once


#define IDC_BUTTON_GAMELIST 0
#define IDC_LISTBOX_GAMELISTING 1
#define IDC_BUTTON_GAMEADD 2

#define IDC_STATIC_GAMENAME 4
#define IDC_STATIC_GAMEGENRE 5
#define IDC_STATIC_GAMEPLATFORM   6
#define IDC_STATIC_GAMERELEASEYEAR 7
#define IDC_STATIC_GAMEPLAYYEAR 8

#define IDC_PICTUREBOX_GAMETITLE 9

#define IDC_STATIC_GAMENAME_TXT 11
#define IDC_STATIC_GAMEGENRE_TXT 12
#define IDC_STATIC_GAMEPLATFORM_TXT   13
#define IDC_STATIC_GAMERELEASEYEAR_TXT 14
#define IDC_STATIC_GAMEPLAYYEAR_TXT 15


#define IDC_PICTUREBOX_GAMETITLE3 16
#define	IDC_EDITBOX_GAMESEARCH 17

//////////////////////////////////////////////////////////
//검색 결과를 위한 패널
//////////////////////////////////////////////////////////
#define IDC_SEARCH_LISTBOX_GAMELISTING 18
#define IDC_SEARCH_PICTUREBOX_GAMETITLE 19

#define IDC_SEARCH_STATIC_GAMENAME_TXT 20
#define IDC_SEARCH_STATIC_GAMEGENRE_TXT 21
#define IDC_SEARCH_STATIC_GAMEPLATFORM_TXT   22
#define IDC_SEARCH_STATIC_GAMERELEASEYEAR_TXT 23
#define IDC_SEARCH_STATIC_GAMEPLAYYEAR_TXT 24

#define IDC_SEARCH_STATIC_GAMENAME 25
#define IDC_SEARCH_STATIC_GAMEGENRE 26
#define IDC_SEARCH_STATIC_GAMEPLATFORM  27
#define IDC_SEARCH_STATIC_GAMERELEASEYEAR 28
#define IDC_SEARCH_STATIC_GAMEPLAYYEAR 29

//////////////////////////////////////////////////////////
//게임 추가를 위한 패널
//////////////////////////////////////////////////////////
#define	IDC_GAMEADD_EDITBOX_NAME 30
#define	IDC_GAMEADD_COMBOBOX_GENRE 31
#define	IDC_GAMEADD_COMBOBOX_PLATFORM 32
#define	IDC_GAMEADD_COMBOBOX_RELEASE 33
#define	IDC_GAMEADD_COMBOBOX_PLAY 34
#define IDC_GAMEADD_BUTTON_OK 35
#define IDC_GAMEADD_GET_TITLEIMAGE 36
#define IDC_GAMEADD_GET_AUDIOFILE 37
#define IDC_GAMEADD_GET_TITLEIMAGE_NAME 38
#define IDC_GAMEADD_GET_AUDIOFILE_NAME 39
#define IDC_GAMEADD_EDIT_MEMO 40

#define IDC_GAMEADD_STATIC_GAMENAME 41
#define IDC_GAMEADD_STATIC_GAMEGENRE 42
#define IDC_GAMEADD_STATIC_GAMEPLATFORM 43
#define IDC_GAMEADD_STATIC_GAMERELEASEYEAR 44
#define IDC_GAMEADD_STATIC_GAMEPLAYYEAR 45

#define IDC_GAMEADD_EDIT_MEMO_NAME 46


#define GUI_BASE			1000

#define GUI_STATIC			GUI_BASE + 0
#define GUI_BUTTON			GUI_BASE + 1
#define GUI_CHECKBOX		GUI_BASE + 2
#define GUI_RADIOBUTTON		GUI_BASE + 3
#define GUI_COMBOBOX		GUI_BASE + 4
#define GUI_SLIDER			GUI_BASE + 5
#define GUI_EDITBOX			GUI_BASE + 6
#define GUI_IMEEDITBOX		GUI_BASE + 7
#define GUI_LISTBOX			GUI_BASE + 8
#define GUI_CONTROL			GUI_BASE + 9
#define GUI_IMAGE			GUI_BASE + 10

#define GUI_TEXTBOX			GUI_BASE + 11

#define PANNEL_BASE				0
#define PANNEL_MENU				PANNEL_BASE + 1
#define PANNEL_GAMEINFO			PANNEL_BASE + 2
#define PANNEL_GAMEPRESENTATION	PANNEL_BASE + 3
#define PANNEL_SEARCHRESULT			PANNEL_BASE + 4
#define PANNEL_GAMEADD			PANNEL_BASE + 5


